[package]
name = "vpb"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0/MIT"
description = "key-value proto buffer for veladb"

[features]
default = ["std"]
full = ["sea-std", "xxhash64-std", "crc32-std"]
std = ["prost/std", "serde/std"]
js = ["getrandom/js"]

# enable seahash checksum
sea = ["seahash", "lazy_static"]
sea-std = ["seahash/use_std", "sea"]

# enable xxhash64 checksum
xxhash64 = ["xxhash-rust/xxh64", "rand", "lazy_static"]
xxhash64-std = ["rand/default", "xxhash64"]

# enable crc32 checksum
crc32 = ["crc32fast"]
crc32-std = ["crc32fast/std"]

[dependencies]
crc32fast = { version = "1.3", optional = true, default-features = false }
getrandom = { version = "0.2", optional = true }
lazy_static = { version = "1.4", optional = true }
prost = { version = "0.11", default-features = false, features = ["prost-derive"] }
rand = { version = "0.8", optional = true, default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
seahash = { version = "4.1", optional = true }
xxhash-rust = { version = "0.8", optional = true, default-features = false }

[build-dependencies]
prost-build = "0.11"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]