[package]
name = "vpb"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0/MIT"
description = "a placeholder"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
